const items = [
  {
    id: 1,
    name: "Gaurav Taneja",
    followers_count: "3.5 Million",
    social_media_name: "Flying Beast",
    img: "images/gt.png",
    post_engagement_rate: 11.7,
    social_media_handle: "taneja.gaurav",
    likes: "420k",
    sex: "male",
    category: "lifestyle",
  },
  {
    id: 2,
    name: "Avneet Kaur",
    followers_count: "32 Million",
    social_media_name: "Avneet Kaur",
    img: "images/ak.png",
    post_engagement_rate: 21.2,
    social_media_handle: "avneetkaur_13",
    likes: "920k",
    sex: "female",
    category: "fashion",
  },
  {
    id: 3,
    name: "Naman Mathur",
    followers_count: "5.5 Million",
    social_media_name: "Mortal",
    img: "images/nm.png",
    post_engagement_rate: 15.3,
    social_media_handle: "ig_mortal",
    likes: "620k",
    sex: "male",
    category: "gaming",
  },
  {
    id: 4,
    name: "Barkha Singh",
    followers_count: "2.9 Million",
    social_media_name: "Barkha Singh",
    img: "images/bs.png",
    post_engagement_rate: 8.9,
    social_media_handle: "barkhasingh0308",
    likes: "220k",
    sex: "female",
    category: "fashion",
  },
  {
    id: 5,
    name: "Ahsaas Channa",
    followers_count: "3.5 Million",
    social_media_name: "Ahsaas",
    img: "images/ac.png",
    post_engagement_rate: 13,
    social_media_handle: "ahsaasy_",
    likes: "120k",
    sex: "female",
    category: "fashion",
  },
  {
    id: 6,
    name: "Gaurav Chaudary",
    followers_count: "2.3 Million",
    social_media_name: "Technincal Guruji",
    img: "images/gc.png",
    post_engagement_rate: 10.2,
    social_media_handle: "technicalguruji",
    likes: "140k",
    sex: "male",
    category: "tech",
  },
];

export default items;
